apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: oes-argo-rollout
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: oes-argo-rollout
  template:
    metadata:
      labels:
        app: oes-argo-rollout
    spec:
      containers:
        - name: rollouts-baseline
          image: docker.io/opsmxdev/issuegen:v3.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
  strategy:
    canary:
      analysis:
        templates:
          - templateName: oes-analysis-job
        startingStep: 2
        args:
          - name: canary-hash
            valueFrom:
              podTemplateHashValue: Latest
          - name: baseline-hash
            valueFrom:
              podTemplateHashValue: Stable
          - name: experiment-hash
            value: "dummy-hash-123"
      canaryService: canary-svc
      stableService: production-svc
      trafficRouting:
        nginx:
          stableIngress: prod-ingress
      steps:
        - setWeight: 20
        - pause: { duration: 60s }
        - setWeight: 40
        - pause: { duration: 180s }
        - setWeight: 80
        - pause: { duration: 60s }
