apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: oes-argo-rollout
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: oes-argo-rollout
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus_io_path: /mgmt/prometheus
        prometheus_io_port: "8088"
      labels:
        app: oes-argo-rollout
    spec:
      containers:
        - name: rollouts-baseline
          image: docker.io/opsmxdev/issuegen:v3.1.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
  strategy:
    canary:
      canaryService: canary-svc
      stableService: production-svc
      trafficRouting:
        nginx:
          stableIngress: prod-ingress
      steps:
        - setWeight: 50
        - pause: { duration: 2m }
        - analysis:
            templates:
              - templateName: oes-analysis-job
            args:
              - name: canary-hash
                valueFrom:
                  podTemplateHashValue: Latest
              - name: baseline-hash
                valueFrom:
                  podTemplateHashValue: Stable
              - name: experiment-hash
                value: "dummy-hash-123"        
        - setWeight: 80
        - pause: { duration: 2m }
        - analysis:
            templates:
              - templateName: oes-analysis-job
            args:
              - name: canary-hash
                valueFrom:
                  podTemplateHashValue: Latest
              - name: baseline-hash
                valueFrom:
                  podTemplateHashValue: Stable
              - name: experiment-hash
                value: "dummy-hash-123"         
        - setWeight: 90
        - pause: { duration: 2m }
        - analysis:
            templates:
              - templateName: oes-analysis-job
            args:
              - name: canary-hash
                valueFrom:
                  podTemplateHashValue: Latest
              - name: baseline-hash
                valueFrom:
                  podTemplateHashValue: Stable
              - name: experiment-hash
                value: "dummy-hash-123" 
